import { CountdownEvent } from '../context/EventsContext';

export function getSampleEvents(): CountdownEvent[] {
  const now = new Date();
  const year = now.getFullYear();

  return [
    {
      id: 'sample-1',
      title: 'New Year ' + (year + 1),
      emoji: '🎆',
      targetDate: new Date(year + 1, 0, 1).toISOString(),
      createdDate: now.toISOString(),
      startDate: new Date(year, 0, 1).toISOString(),
      color: 'lavender',
      category: 'holiday',
      isCountUp: false,
      isPinned: true,
      size: 'large',
    },
    {
      id: 'sample-2',
      title: 'Summer Vacation',
      emoji: '🏖️',
      targetDate: new Date(year, 5, 21).toISOString(),
      createdDate: now.toISOString(),
      startDate: now.toISOString(),
      color: 'ocean',
      category: 'vacation',
      isCountUp: false,
      isPinned: false,
      size: 'medium',
    },
    {
      id: 'sample-3',
      title: 'Birthday',
      emoji: '🎂',
      targetDate: new Date(year, 8, 15).toISOString(),
      createdDate: now.toISOString(),
      startDate: now.toISOString(),
      color: 'rose',
      category: 'birthday',
      isCountUp: false,
      isPinned: false,
      size: 'medium',
    },
    {
      id: 'sample-4',
      title: 'Year Progress',
      emoji: '📅',
      targetDate: new Date(year, 11, 31).toISOString(),
      createdDate: now.toISOString(),
      startDate: new Date(year, 0, 1).toISOString(),
      color: 'aurora',
      category: 'custom',
      isCountUp: false,
      isPinned: true,
      size: 'small',
    },
    {
      id: 'sample-5',
      title: 'Fitness Goal',
      emoji: '💪',
      targetDate: new Date(year, 11, 1).toISOString(),
      createdDate: now.toISOString(),
      startDate: now.toISOString(),
      color: 'mint',
      category: 'fitness',
      isCountUp: false,
      isPinned: false,
      size: 'small',
    },
    {
      id: 'sample-6',
      title: 'Halloween',
      emoji: '🎃',
      targetDate: new Date(year, 9, 31).toISOString(),
      createdDate: now.toISOString(),
      startDate: now.toISOString(),
      color: 'ember',
      category: 'holiday',
      isCountUp: false,
      isPinned: false,
      size: 'medium',
    },
  ];
}
